name: Roman's Chiro
favicon: null
layout_spectrum: 0.4944582830648869
typography_spectrum: 0.03144962200894952
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.15005098562687635
  lightness: 0.22396305645816028
  saturation: 0.9183289620559663
  rhythmicContrast: 0.3658335900399834
purpose: []
