name: Roman's Chiro
favicon: null
layout_spectrum: 0
typography_spectrum: 0.03144962200894952
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4f3f6'
    - '#4774b8'
    - '#b0d4ee'
    - '#85a1c9'
    - '#3c5f95'
  brandStrength: 0
  lightness: 0.22396305645816028
  saturation: 0.9183289620559663
  rhythmicContrast: 0.3658335900399834
purpose: []
